// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NotificacaoEx.proto

package exchange;

public final class NotificacaoEx {
  private NotificacaoEx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code exchange.TipoNotificacao}
   */
  public enum TipoNotificacao
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CRIACAO = 1;</code>
     */
    CRIACAO(1),
    /**
     * <code>LICITACAO = 2;</code>
     */
    LICITACAO(2),
    /**
     * <code>FIM = 3;</code>
     */
    FIM(3),
    ;

    /**
     * <code>CRIACAO = 1;</code>
     */
    public static final int CRIACAO_VALUE = 1;
    /**
     * <code>LICITACAO = 2;</code>
     */
    public static final int LICITACAO_VALUE = 2;
    /**
     * <code>FIM = 3;</code>
     */
    public static final int FIM_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TipoNotificacao valueOf(int value) {
      return forNumber(value);
    }

    public static TipoNotificacao forNumber(int value) {
      switch (value) {
        case 1: return CRIACAO;
        case 2: return LICITACAO;
        case 3: return FIM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TipoNotificacao>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TipoNotificacao> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TipoNotificacao>() {
            public TipoNotificacao findValueByNumber(int number) {
              return TipoNotificacao.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return exchange.NotificacaoEx.getDescriptor().getEnumTypes().get(0);
    }

    private static final TipoNotificacao[] VALUES = values();

    public static TipoNotificacao valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TipoNotificacao(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:exchange.TipoNotificacao)
  }

  /**
   * Protobuf enum {@code exchange.TipoAcao}
   */
  public enum TipoAcao
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LEILAO = 1;</code>
     */
    LEILAO(1),
    /**
     * <code>EMISSAO = 2;</code>
     */
    EMISSAO(2),
    ;

    /**
     * <code>LEILAO = 1;</code>
     */
    public static final int LEILAO_VALUE = 1;
    /**
     * <code>EMISSAO = 2;</code>
     */
    public static final int EMISSAO_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TipoAcao valueOf(int value) {
      return forNumber(value);
    }

    public static TipoAcao forNumber(int value) {
      switch (value) {
        case 1: return LEILAO;
        case 2: return EMISSAO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TipoAcao>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TipoAcao> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TipoAcao>() {
            public TipoAcao findValueByNumber(int number) {
              return TipoAcao.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return exchange.NotificacaoEx.getDescriptor().getEnumTypes().get(1);
    }

    private static final TipoAcao[] VALUES = values();

    public static TipoAcao valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TipoAcao(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:exchange.TipoAcao)
  }

  public interface NotificacaoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:exchange.Notificacao)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .exchange.TipoNotificacao tipo = 1 [default = CRIACAO];</code>
     */
    boolean hasTipo();
    /**
     * <code>required .exchange.TipoNotificacao tipo = 1 [default = CRIACAO];</code>
     */
    exchange.NotificacaoEx.TipoNotificacao getTipo();

    /**
     * <code>required .exchange.TipoAcao tipoMensagem = 2 [default = LEILAO];</code>
     */
    boolean hasTipoMensagem();
    /**
     * <code>required .exchange.TipoAcao tipoMensagem = 2 [default = LEILAO];</code>
     */
    exchange.NotificacaoEx.TipoAcao getTipoMensagem();

    /**
     * <code>required string empresa = 3;</code>
     */
    boolean hasEmpresa();
    /**
     * <code>required string empresa = 3;</code>
     */
    java.lang.String getEmpresa();
    /**
     * <code>required string empresa = 3;</code>
     */
    com.google.protobuf.ByteString
        getEmpresaBytes();

    /**
     * <code>required int64 montante = 4;</code>
     */
    boolean hasMontante();
    /**
     * <code>required int64 montante = 4;</code>
     */
    long getMontante();

    /**
     * <code>optional float taxa = 5;</code>
     */
    boolean hasTaxa();
    /**
     * <code>optional float taxa = 5;</code>
     */
    float getTaxa();

    /**
     * <code>optional int64 tempo = 6;</code>
     */
    boolean hasTempo();
    /**
     * <code>optional int64 tempo = 6;</code>
     */
    long getTempo();

    /**
     * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
     */
    boolean hasResultado();
    /**
     * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
     */
    exchange.NotificacaoEx.ResultadoAcao getResultado();
    /**
     * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
     */
    exchange.NotificacaoEx.ResultadoAcaoOrBuilder getResultadoOrBuilder();
  }
  /**
   * Protobuf type {@code exchange.Notificacao}
   */
  public  static final class Notificacao extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:exchange.Notificacao)
      NotificacaoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Notificacao.newBuilder() to construct.
    private Notificacao(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Notificacao() {
      tipo_ = 1;
      tipoMensagem_ = 1;
      empresa_ = "";
      montante_ = 0L;
      taxa_ = 0F;
      tempo_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Notificacao(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              exchange.NotificacaoEx.TipoNotificacao value = exchange.NotificacaoEx.TipoNotificacao.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                tipo_ = rawValue;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              exchange.NotificacaoEx.TipoAcao value = exchange.NotificacaoEx.TipoAcao.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                tipoMensagem_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              empresa_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              montante_ = input.readInt64();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              taxa_ = input.readFloat();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              tempo_ = input.readInt64();
              break;
            }
            case 58: {
              exchange.NotificacaoEx.ResultadoAcao.Builder subBuilder = null;
              if (((bitField0_ & 0x00000040) == 0x00000040)) {
                subBuilder = resultado_.toBuilder();
              }
              resultado_ = input.readMessage(exchange.NotificacaoEx.ResultadoAcao.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resultado_);
                resultado_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000040;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return exchange.NotificacaoEx.internal_static_exchange_Notificacao_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return exchange.NotificacaoEx.internal_static_exchange_Notificacao_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              exchange.NotificacaoEx.Notificacao.class, exchange.NotificacaoEx.Notificacao.Builder.class);
    }

    private int bitField0_;
    public static final int TIPO_FIELD_NUMBER = 1;
    private int tipo_;
    /**
     * <code>required .exchange.TipoNotificacao tipo = 1 [default = CRIACAO];</code>
     */
    public boolean hasTipo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .exchange.TipoNotificacao tipo = 1 [default = CRIACAO];</code>
     */
    public exchange.NotificacaoEx.TipoNotificacao getTipo() {
      @SuppressWarnings("deprecation")
      exchange.NotificacaoEx.TipoNotificacao result = exchange.NotificacaoEx.TipoNotificacao.valueOf(tipo_);
      return result == null ? exchange.NotificacaoEx.TipoNotificacao.CRIACAO : result;
    }

    public static final int TIPOMENSAGEM_FIELD_NUMBER = 2;
    private int tipoMensagem_;
    /**
     * <code>required .exchange.TipoAcao tipoMensagem = 2 [default = LEILAO];</code>
     */
    public boolean hasTipoMensagem() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .exchange.TipoAcao tipoMensagem = 2 [default = LEILAO];</code>
     */
    public exchange.NotificacaoEx.TipoAcao getTipoMensagem() {
      @SuppressWarnings("deprecation")
      exchange.NotificacaoEx.TipoAcao result = exchange.NotificacaoEx.TipoAcao.valueOf(tipoMensagem_);
      return result == null ? exchange.NotificacaoEx.TipoAcao.LEILAO : result;
    }

    public static final int EMPRESA_FIELD_NUMBER = 3;
    private volatile java.lang.Object empresa_;
    /**
     * <code>required string empresa = 3;</code>
     */
    public boolean hasEmpresa() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string empresa = 3;</code>
     */
    public java.lang.String getEmpresa() {
      java.lang.Object ref = empresa_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          empresa_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string empresa = 3;</code>
     */
    public com.google.protobuf.ByteString
        getEmpresaBytes() {
      java.lang.Object ref = empresa_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        empresa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONTANTE_FIELD_NUMBER = 4;
    private long montante_;
    /**
     * <code>required int64 montante = 4;</code>
     */
    public boolean hasMontante() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int64 montante = 4;</code>
     */
    public long getMontante() {
      return montante_;
    }

    public static final int TAXA_FIELD_NUMBER = 5;
    private float taxa_;
    /**
     * <code>optional float taxa = 5;</code>
     */
    public boolean hasTaxa() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float taxa = 5;</code>
     */
    public float getTaxa() {
      return taxa_;
    }

    public static final int TEMPO_FIELD_NUMBER = 6;
    private long tempo_;
    /**
     * <code>optional int64 tempo = 6;</code>
     */
    public boolean hasTempo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int64 tempo = 6;</code>
     */
    public long getTempo() {
      return tempo_;
    }

    public static final int RESULTADO_FIELD_NUMBER = 7;
    private exchange.NotificacaoEx.ResultadoAcao resultado_;
    /**
     * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
     */
    public boolean hasResultado() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
     */
    public exchange.NotificacaoEx.ResultadoAcao getResultado() {
      return resultado_ == null ? exchange.NotificacaoEx.ResultadoAcao.getDefaultInstance() : resultado_;
    }
    /**
     * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
     */
    public exchange.NotificacaoEx.ResultadoAcaoOrBuilder getResultadoOrBuilder() {
      return resultado_ == null ? exchange.NotificacaoEx.ResultadoAcao.getDefaultInstance() : resultado_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTipo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTipoMensagem()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEmpresa()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMontante()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasResultado()) {
        if (!getResultado().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, tipo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, tipoMensagem_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, empresa_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, montante_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, taxa_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, tempo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeMessage(7, getResultado());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, tipo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, tipoMensagem_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, empresa_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, montante_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, taxa_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, tempo_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getResultado());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof exchange.NotificacaoEx.Notificacao)) {
        return super.equals(obj);
      }
      exchange.NotificacaoEx.Notificacao other = (exchange.NotificacaoEx.Notificacao) obj;

      boolean result = true;
      result = result && (hasTipo() == other.hasTipo());
      if (hasTipo()) {
        result = result && tipo_ == other.tipo_;
      }
      result = result && (hasTipoMensagem() == other.hasTipoMensagem());
      if (hasTipoMensagem()) {
        result = result && tipoMensagem_ == other.tipoMensagem_;
      }
      result = result && (hasEmpresa() == other.hasEmpresa());
      if (hasEmpresa()) {
        result = result && getEmpresa()
            .equals(other.getEmpresa());
      }
      result = result && (hasMontante() == other.hasMontante());
      if (hasMontante()) {
        result = result && (getMontante()
            == other.getMontante());
      }
      result = result && (hasTaxa() == other.hasTaxa());
      if (hasTaxa()) {
        result = result && (
            java.lang.Float.floatToIntBits(getTaxa())
            == java.lang.Float.floatToIntBits(
                other.getTaxa()));
      }
      result = result && (hasTempo() == other.hasTempo());
      if (hasTempo()) {
        result = result && (getTempo()
            == other.getTempo());
      }
      result = result && (hasResultado() == other.hasResultado());
      if (hasResultado()) {
        result = result && getResultado()
            .equals(other.getResultado());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTipo()) {
        hash = (37 * hash) + TIPO_FIELD_NUMBER;
        hash = (53 * hash) + tipo_;
      }
      if (hasTipoMensagem()) {
        hash = (37 * hash) + TIPOMENSAGEM_FIELD_NUMBER;
        hash = (53 * hash) + tipoMensagem_;
      }
      if (hasEmpresa()) {
        hash = (37 * hash) + EMPRESA_FIELD_NUMBER;
        hash = (53 * hash) + getEmpresa().hashCode();
      }
      if (hasMontante()) {
        hash = (37 * hash) + MONTANTE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMontante());
      }
      if (hasTaxa()) {
        hash = (37 * hash) + TAXA_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getTaxa());
      }
      if (hasTempo()) {
        hash = (37 * hash) + TEMPO_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTempo());
      }
      if (hasResultado()) {
        hash = (37 * hash) + RESULTADO_FIELD_NUMBER;
        hash = (53 * hash) + getResultado().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static exchange.NotificacaoEx.Notificacao parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exchange.NotificacaoEx.Notificacao parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exchange.NotificacaoEx.Notificacao parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exchange.NotificacaoEx.Notificacao parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exchange.NotificacaoEx.Notificacao parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exchange.NotificacaoEx.Notificacao parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exchange.NotificacaoEx.Notificacao parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static exchange.NotificacaoEx.Notificacao parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static exchange.NotificacaoEx.Notificacao parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static exchange.NotificacaoEx.Notificacao parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static exchange.NotificacaoEx.Notificacao parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static exchange.NotificacaoEx.Notificacao parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(exchange.NotificacaoEx.Notificacao prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code exchange.Notificacao}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:exchange.Notificacao)
        exchange.NotificacaoEx.NotificacaoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return exchange.NotificacaoEx.internal_static_exchange_Notificacao_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return exchange.NotificacaoEx.internal_static_exchange_Notificacao_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                exchange.NotificacaoEx.Notificacao.class, exchange.NotificacaoEx.Notificacao.Builder.class);
      }

      // Construct using exchange.NotificacaoEx.Notificacao.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getResultadoFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tipo_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        tipoMensagem_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        empresa_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        montante_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        taxa_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        tempo_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        if (resultadoBuilder_ == null) {
          resultado_ = null;
        } else {
          resultadoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return exchange.NotificacaoEx.internal_static_exchange_Notificacao_descriptor;
      }

      @java.lang.Override
      public exchange.NotificacaoEx.Notificacao getDefaultInstanceForType() {
        return exchange.NotificacaoEx.Notificacao.getDefaultInstance();
      }

      @java.lang.Override
      public exchange.NotificacaoEx.Notificacao build() {
        exchange.NotificacaoEx.Notificacao result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public exchange.NotificacaoEx.Notificacao buildPartial() {
        exchange.NotificacaoEx.Notificacao result = new exchange.NotificacaoEx.Notificacao(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tipo_ = tipo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tipoMensagem_ = tipoMensagem_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.empresa_ = empresa_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.montante_ = montante_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.taxa_ = taxa_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.tempo_ = tempo_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        if (resultadoBuilder_ == null) {
          result.resultado_ = resultado_;
        } else {
          result.resultado_ = resultadoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof exchange.NotificacaoEx.Notificacao) {
          return mergeFrom((exchange.NotificacaoEx.Notificacao)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(exchange.NotificacaoEx.Notificacao other) {
        if (other == exchange.NotificacaoEx.Notificacao.getDefaultInstance()) return this;
        if (other.hasTipo()) {
          setTipo(other.getTipo());
        }
        if (other.hasTipoMensagem()) {
          setTipoMensagem(other.getTipoMensagem());
        }
        if (other.hasEmpresa()) {
          bitField0_ |= 0x00000004;
          empresa_ = other.empresa_;
          onChanged();
        }
        if (other.hasMontante()) {
          setMontante(other.getMontante());
        }
        if (other.hasTaxa()) {
          setTaxa(other.getTaxa());
        }
        if (other.hasTempo()) {
          setTempo(other.getTempo());
        }
        if (other.hasResultado()) {
          mergeResultado(other.getResultado());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTipo()) {
          return false;
        }
        if (!hasTipoMensagem()) {
          return false;
        }
        if (!hasEmpresa()) {
          return false;
        }
        if (!hasMontante()) {
          return false;
        }
        if (hasResultado()) {
          if (!getResultado().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        exchange.NotificacaoEx.Notificacao parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (exchange.NotificacaoEx.Notificacao) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int tipo_ = 1;
      /**
       * <code>required .exchange.TipoNotificacao tipo = 1 [default = CRIACAO];</code>
       */
      public boolean hasTipo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .exchange.TipoNotificacao tipo = 1 [default = CRIACAO];</code>
       */
      public exchange.NotificacaoEx.TipoNotificacao getTipo() {
        @SuppressWarnings("deprecation")
        exchange.NotificacaoEx.TipoNotificacao result = exchange.NotificacaoEx.TipoNotificacao.valueOf(tipo_);
        return result == null ? exchange.NotificacaoEx.TipoNotificacao.CRIACAO : result;
      }
      /**
       * <code>required .exchange.TipoNotificacao tipo = 1 [default = CRIACAO];</code>
       */
      public Builder setTipo(exchange.NotificacaoEx.TipoNotificacao value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        tipo_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .exchange.TipoNotificacao tipo = 1 [default = CRIACAO];</code>
       */
      public Builder clearTipo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tipo_ = 1;
        onChanged();
        return this;
      }

      private int tipoMensagem_ = 1;
      /**
       * <code>required .exchange.TipoAcao tipoMensagem = 2 [default = LEILAO];</code>
       */
      public boolean hasTipoMensagem() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .exchange.TipoAcao tipoMensagem = 2 [default = LEILAO];</code>
       */
      public exchange.NotificacaoEx.TipoAcao getTipoMensagem() {
        @SuppressWarnings("deprecation")
        exchange.NotificacaoEx.TipoAcao result = exchange.NotificacaoEx.TipoAcao.valueOf(tipoMensagem_);
        return result == null ? exchange.NotificacaoEx.TipoAcao.LEILAO : result;
      }
      /**
       * <code>required .exchange.TipoAcao tipoMensagem = 2 [default = LEILAO];</code>
       */
      public Builder setTipoMensagem(exchange.NotificacaoEx.TipoAcao value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        tipoMensagem_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .exchange.TipoAcao tipoMensagem = 2 [default = LEILAO];</code>
       */
      public Builder clearTipoMensagem() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tipoMensagem_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object empresa_ = "";
      /**
       * <code>required string empresa = 3;</code>
       */
      public boolean hasEmpresa() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string empresa = 3;</code>
       */
      public java.lang.String getEmpresa() {
        java.lang.Object ref = empresa_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            empresa_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string empresa = 3;</code>
       */
      public com.google.protobuf.ByteString
          getEmpresaBytes() {
        java.lang.Object ref = empresa_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          empresa_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string empresa = 3;</code>
       */
      public Builder setEmpresa(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        empresa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string empresa = 3;</code>
       */
      public Builder clearEmpresa() {
        bitField0_ = (bitField0_ & ~0x00000004);
        empresa_ = getDefaultInstance().getEmpresa();
        onChanged();
        return this;
      }
      /**
       * <code>required string empresa = 3;</code>
       */
      public Builder setEmpresaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        empresa_ = value;
        onChanged();
        return this;
      }

      private long montante_ ;
      /**
       * <code>required int64 montante = 4;</code>
       */
      public boolean hasMontante() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int64 montante = 4;</code>
       */
      public long getMontante() {
        return montante_;
      }
      /**
       * <code>required int64 montante = 4;</code>
       */
      public Builder setMontante(long value) {
        bitField0_ |= 0x00000008;
        montante_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 montante = 4;</code>
       */
      public Builder clearMontante() {
        bitField0_ = (bitField0_ & ~0x00000008);
        montante_ = 0L;
        onChanged();
        return this;
      }

      private float taxa_ ;
      /**
       * <code>optional float taxa = 5;</code>
       */
      public boolean hasTaxa() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float taxa = 5;</code>
       */
      public float getTaxa() {
        return taxa_;
      }
      /**
       * <code>optional float taxa = 5;</code>
       */
      public Builder setTaxa(float value) {
        bitField0_ |= 0x00000010;
        taxa_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float taxa = 5;</code>
       */
      public Builder clearTaxa() {
        bitField0_ = (bitField0_ & ~0x00000010);
        taxa_ = 0F;
        onChanged();
        return this;
      }

      private long tempo_ ;
      /**
       * <code>optional int64 tempo = 6;</code>
       */
      public boolean hasTempo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int64 tempo = 6;</code>
       */
      public long getTempo() {
        return tempo_;
      }
      /**
       * <code>optional int64 tempo = 6;</code>
       */
      public Builder setTempo(long value) {
        bitField0_ |= 0x00000020;
        tempo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 tempo = 6;</code>
       */
      public Builder clearTempo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        tempo_ = 0L;
        onChanged();
        return this;
      }

      private exchange.NotificacaoEx.ResultadoAcao resultado_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          exchange.NotificacaoEx.ResultadoAcao, exchange.NotificacaoEx.ResultadoAcao.Builder, exchange.NotificacaoEx.ResultadoAcaoOrBuilder> resultadoBuilder_;
      /**
       * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
       */
      public boolean hasResultado() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
       */
      public exchange.NotificacaoEx.ResultadoAcao getResultado() {
        if (resultadoBuilder_ == null) {
          return resultado_ == null ? exchange.NotificacaoEx.ResultadoAcao.getDefaultInstance() : resultado_;
        } else {
          return resultadoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
       */
      public Builder setResultado(exchange.NotificacaoEx.ResultadoAcao value) {
        if (resultadoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resultado_ = value;
          onChanged();
        } else {
          resultadoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
       */
      public Builder setResultado(
          exchange.NotificacaoEx.ResultadoAcao.Builder builderForValue) {
        if (resultadoBuilder_ == null) {
          resultado_ = builderForValue.build();
          onChanged();
        } else {
          resultadoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
       */
      public Builder mergeResultado(exchange.NotificacaoEx.ResultadoAcao value) {
        if (resultadoBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040) &&
              resultado_ != null &&
              resultado_ != exchange.NotificacaoEx.ResultadoAcao.getDefaultInstance()) {
            resultado_ =
              exchange.NotificacaoEx.ResultadoAcao.newBuilder(resultado_).mergeFrom(value).buildPartial();
          } else {
            resultado_ = value;
          }
          onChanged();
        } else {
          resultadoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000040;
        return this;
      }
      /**
       * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
       */
      public Builder clearResultado() {
        if (resultadoBuilder_ == null) {
          resultado_ = null;
          onChanged();
        } else {
          resultadoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      /**
       * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
       */
      public exchange.NotificacaoEx.ResultadoAcao.Builder getResultadoBuilder() {
        bitField0_ |= 0x00000040;
        onChanged();
        return getResultadoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
       */
      public exchange.NotificacaoEx.ResultadoAcaoOrBuilder getResultadoOrBuilder() {
        if (resultadoBuilder_ != null) {
          return resultadoBuilder_.getMessageOrBuilder();
        } else {
          return resultado_ == null ?
              exchange.NotificacaoEx.ResultadoAcao.getDefaultInstance() : resultado_;
        }
      }
      /**
       * <code>optional .exchange.ResultadoAcao resultado = 7;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          exchange.NotificacaoEx.ResultadoAcao, exchange.NotificacaoEx.ResultadoAcao.Builder, exchange.NotificacaoEx.ResultadoAcaoOrBuilder> 
          getResultadoFieldBuilder() {
        if (resultadoBuilder_ == null) {
          resultadoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              exchange.NotificacaoEx.ResultadoAcao, exchange.NotificacaoEx.ResultadoAcao.Builder, exchange.NotificacaoEx.ResultadoAcaoOrBuilder>(
                  getResultado(),
                  getParentForChildren(),
                  isClean());
          resultado_ = null;
        }
        return resultadoBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:exchange.Notificacao)
    }

    // @@protoc_insertion_point(class_scope:exchange.Notificacao)
    private static final exchange.NotificacaoEx.Notificacao DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new exchange.NotificacaoEx.Notificacao();
    }

    public static exchange.NotificacaoEx.Notificacao getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Notificacao>
        PARSER = new com.google.protobuf.AbstractParser<Notificacao>() {
      @java.lang.Override
      public Notificacao parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Notificacao(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Notificacao> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Notificacao> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public exchange.NotificacaoEx.Notificacao getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResultadoAcaoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:exchange.ResultadoAcao)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .exchange.TipoAcao tipo = 1 [default = LEILAO];</code>
     */
    boolean hasTipo();
    /**
     * <code>required .exchange.TipoAcao tipo = 1 [default = LEILAO];</code>
     */
    exchange.NotificacaoEx.TipoAcao getTipo();

    /**
     * <code>required string texto = 3;</code>
     */
    boolean hasTexto();
    /**
     * <code>required string texto = 3;</code>
     */
    java.lang.String getTexto();
    /**
     * <code>required string texto = 3;</code>
     */
    com.google.protobuf.ByteString
        getTextoBytes();
  }
  /**
   * Protobuf type {@code exchange.ResultadoAcao}
   */
  public  static final class ResultadoAcao extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:exchange.ResultadoAcao)
      ResultadoAcaoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResultadoAcao.newBuilder() to construct.
    private ResultadoAcao(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResultadoAcao() {
      tipo_ = 1;
      texto_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResultadoAcao(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              exchange.NotificacaoEx.TipoAcao value = exchange.NotificacaoEx.TipoAcao.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                tipo_ = rawValue;
              }
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              texto_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return exchange.NotificacaoEx.internal_static_exchange_ResultadoAcao_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return exchange.NotificacaoEx.internal_static_exchange_ResultadoAcao_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              exchange.NotificacaoEx.ResultadoAcao.class, exchange.NotificacaoEx.ResultadoAcao.Builder.class);
    }

    private int bitField0_;
    public static final int TIPO_FIELD_NUMBER = 1;
    private int tipo_;
    /**
     * <code>required .exchange.TipoAcao tipo = 1 [default = LEILAO];</code>
     */
    public boolean hasTipo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .exchange.TipoAcao tipo = 1 [default = LEILAO];</code>
     */
    public exchange.NotificacaoEx.TipoAcao getTipo() {
      @SuppressWarnings("deprecation")
      exchange.NotificacaoEx.TipoAcao result = exchange.NotificacaoEx.TipoAcao.valueOf(tipo_);
      return result == null ? exchange.NotificacaoEx.TipoAcao.LEILAO : result;
    }

    public static final int TEXTO_FIELD_NUMBER = 3;
    private volatile java.lang.Object texto_;
    /**
     * <code>required string texto = 3;</code>
     */
    public boolean hasTexto() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string texto = 3;</code>
     */
    public java.lang.String getTexto() {
      java.lang.Object ref = texto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          texto_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string texto = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTextoBytes() {
      java.lang.Object ref = texto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        texto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTipo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTexto()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, tipo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, texto_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, tipo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, texto_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof exchange.NotificacaoEx.ResultadoAcao)) {
        return super.equals(obj);
      }
      exchange.NotificacaoEx.ResultadoAcao other = (exchange.NotificacaoEx.ResultadoAcao) obj;

      boolean result = true;
      result = result && (hasTipo() == other.hasTipo());
      if (hasTipo()) {
        result = result && tipo_ == other.tipo_;
      }
      result = result && (hasTexto() == other.hasTexto());
      if (hasTexto()) {
        result = result && getTexto()
            .equals(other.getTexto());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTipo()) {
        hash = (37 * hash) + TIPO_FIELD_NUMBER;
        hash = (53 * hash) + tipo_;
      }
      if (hasTexto()) {
        hash = (37 * hash) + TEXTO_FIELD_NUMBER;
        hash = (53 * hash) + getTexto().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static exchange.NotificacaoEx.ResultadoAcao parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static exchange.NotificacaoEx.ResultadoAcao parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(exchange.NotificacaoEx.ResultadoAcao prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code exchange.ResultadoAcao}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:exchange.ResultadoAcao)
        exchange.NotificacaoEx.ResultadoAcaoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return exchange.NotificacaoEx.internal_static_exchange_ResultadoAcao_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return exchange.NotificacaoEx.internal_static_exchange_ResultadoAcao_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                exchange.NotificacaoEx.ResultadoAcao.class, exchange.NotificacaoEx.ResultadoAcao.Builder.class);
      }

      // Construct using exchange.NotificacaoEx.ResultadoAcao.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tipo_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        texto_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return exchange.NotificacaoEx.internal_static_exchange_ResultadoAcao_descriptor;
      }

      @java.lang.Override
      public exchange.NotificacaoEx.ResultadoAcao getDefaultInstanceForType() {
        return exchange.NotificacaoEx.ResultadoAcao.getDefaultInstance();
      }

      @java.lang.Override
      public exchange.NotificacaoEx.ResultadoAcao build() {
        exchange.NotificacaoEx.ResultadoAcao result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public exchange.NotificacaoEx.ResultadoAcao buildPartial() {
        exchange.NotificacaoEx.ResultadoAcao result = new exchange.NotificacaoEx.ResultadoAcao(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.tipo_ = tipo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.texto_ = texto_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof exchange.NotificacaoEx.ResultadoAcao) {
          return mergeFrom((exchange.NotificacaoEx.ResultadoAcao)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(exchange.NotificacaoEx.ResultadoAcao other) {
        if (other == exchange.NotificacaoEx.ResultadoAcao.getDefaultInstance()) return this;
        if (other.hasTipo()) {
          setTipo(other.getTipo());
        }
        if (other.hasTexto()) {
          bitField0_ |= 0x00000002;
          texto_ = other.texto_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTipo()) {
          return false;
        }
        if (!hasTexto()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        exchange.NotificacaoEx.ResultadoAcao parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (exchange.NotificacaoEx.ResultadoAcao) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int tipo_ = 1;
      /**
       * <code>required .exchange.TipoAcao tipo = 1 [default = LEILAO];</code>
       */
      public boolean hasTipo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .exchange.TipoAcao tipo = 1 [default = LEILAO];</code>
       */
      public exchange.NotificacaoEx.TipoAcao getTipo() {
        @SuppressWarnings("deprecation")
        exchange.NotificacaoEx.TipoAcao result = exchange.NotificacaoEx.TipoAcao.valueOf(tipo_);
        return result == null ? exchange.NotificacaoEx.TipoAcao.LEILAO : result;
      }
      /**
       * <code>required .exchange.TipoAcao tipo = 1 [default = LEILAO];</code>
       */
      public Builder setTipo(exchange.NotificacaoEx.TipoAcao value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        tipo_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .exchange.TipoAcao tipo = 1 [default = LEILAO];</code>
       */
      public Builder clearTipo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        tipo_ = 1;
        onChanged();
        return this;
      }

      private java.lang.Object texto_ = "";
      /**
       * <code>required string texto = 3;</code>
       */
      public boolean hasTexto() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string texto = 3;</code>
       */
      public java.lang.String getTexto() {
        java.lang.Object ref = texto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            texto_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string texto = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTextoBytes() {
        java.lang.Object ref = texto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          texto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string texto = 3;</code>
       */
      public Builder setTexto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        texto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string texto = 3;</code>
       */
      public Builder clearTexto() {
        bitField0_ = (bitField0_ & ~0x00000002);
        texto_ = getDefaultInstance().getTexto();
        onChanged();
        return this;
      }
      /**
       * <code>required string texto = 3;</code>
       */
      public Builder setTextoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        texto_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:exchange.ResultadoAcao)
    }

    // @@protoc_insertion_point(class_scope:exchange.ResultadoAcao)
    private static final exchange.NotificacaoEx.ResultadoAcao DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new exchange.NotificacaoEx.ResultadoAcao();
    }

    public static exchange.NotificacaoEx.ResultadoAcao getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ResultadoAcao>
        PARSER = new com.google.protobuf.AbstractParser<ResultadoAcao>() {
      @java.lang.Override
      public ResultadoAcao parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResultadoAcao(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResultadoAcao> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResultadoAcao> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public exchange.NotificacaoEx.ResultadoAcao getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exchange_Notificacao_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exchange_Notificacao_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_exchange_ResultadoAcao_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_exchange_ResultadoAcao_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023NotificacaoEx.proto\022\010exchange\"\335\001\n\013Noti" +
      "ficacao\0220\n\004tipo\030\001 \002(\0162\031.exchange.TipoNot" +
      "ificacao:\007CRIACAO\0220\n\014tipoMensagem\030\002 \002(\0162" +
      "\022.exchange.TipoAcao:\006LEILAO\022\017\n\007empresa\030\003" +
      " \002(\t\022\020\n\010montante\030\004 \002(\003\022\014\n\004taxa\030\005 \001(\002\022\r\n\005" +
      "tempo\030\006 \001(\003\022*\n\tresultado\030\007 \001(\0132\027.exchang" +
      "e.ResultadoAcao\"H\n\rResultadoAcao\022(\n\004tipo" +
      "\030\001 \002(\0162\022.exchange.TipoAcao:\006LEILAO\022\r\n\005te" +
      "xto\030\003 \002(\t*6\n\017TipoNotificacao\022\013\n\007CRIACAO\020" +
      "\001\022\r\n\tLICITACAO\020\002\022\007\n\003FIM\020\003*#\n\010TipoAcao\022\n\n" +
      "\006LEILAO\020\001\022\013\n\007EMISSAO\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_exchange_Notificacao_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_exchange_Notificacao_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exchange_Notificacao_descriptor,
        new java.lang.String[] { "Tipo", "TipoMensagem", "Empresa", "Montante", "Taxa", "Tempo", "Resultado", });
    internal_static_exchange_ResultadoAcao_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_exchange_ResultadoAcao_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_exchange_ResultadoAcao_descriptor,
        new java.lang.String[] { "Tipo", "Texto", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
