%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.4.0

-ifndef(ccs).
-define(ccs, true).

-define(ccs_gpb_version, "4.4.0").

-ifndef('AUTENTICACAO_PB_H').
-define('AUTENTICACAO_PB_H', true).
-record('Autenticacao',
        {username               :: iolist(),        % = 1
         password               :: iolist()         % = 2
        }).
-endif.

-ifndef('RESPOSTAAUTENTICACAO_PB_H').
-define('RESPOSTAAUTENTICACAO_PB_H', true).
-record('RespostaAutenticacao',
        {sucesso                :: boolean() | 0 | 1, % = 1
         papel                  :: iolist() | undefined, % = 2
         leilaoSubscrito        :: boolean() | 0 | 1 | undefined, % = 3
         emissaoSubscrita       :: boolean() | 0 | 1 | undefined, % = 4
         empresasSubscritas = [] :: [iolist()] | undefined % = 5
        }).
-endif.

-ifndef('MENSAGEMUTILIZADOR_PB_H').
-define('MENSAGEMUTILIZADOR_PB_H', true).
-record('MensagemUtilizador',
        {tipo = 'LEILAO'        :: 'LEILAO' | 'EMISSAO' | 'SUBSCRICAO' | integer(), % = 1, enum TipoMensagem
         tipoUtilizador = 'EMPRESA' :: 'EMPRESA' | 'INVESTIDOR' | integer(), % = 2, enum TipoUtilizador
         utilizador             :: iolist(),        % = 3
         empresa                :: ccs:'MensagemEmpresa'() | undefined, % = 4
         investidor             :: ccs:'MensagemInvestidor'() | undefined, % = 5
         subscricao             :: ccs:'Subscricao'() | undefined % = 6
        }).
-endif.

-ifndef('MENSAGEMEMPRESA_PB_H').
-define('MENSAGEMEMPRESA_PB_H', true).
-record('MensagemEmpresa',
        {leilao                 :: ccs:'CriacaoLeilao'() | undefined, % = 2
         emissao                :: ccs:'EmissaoTaxaFixa'() | undefined % = 3
        }).
-endif.

-ifndef('CRIACAOLEILAO_PB_H').
-define('CRIACAOLEILAO_PB_H', true).
-record('CriacaoLeilao',
        {montante               :: integer(),       % = 1, 32 bits
         taxa                   :: float() | integer() | infinity | '-infinity' | nan, % = 2
         tempo                  :: integer()        % = 3, 32 bits
        }).
-endif.

-ifndef('EMISSAOTAXAFIXA_PB_H').
-define('EMISSAOTAXAFIXA_PB_H', true).
-record('EmissaoTaxaFixa',
        {montante               :: integer(),       % = 1, 32 bits
         tempo                  :: integer()        % = 2, 32 bits
        }).
-endif.

-ifndef('MENSAGEMINVESTIDOR_PB_H').
-define('MENSAGEMINVESTIDOR_PB_H', true).
-record('MensagemInvestidor',
        {leilao                 :: ccs:'LicitacaoLeilao'() | undefined, % = 2
         emissao                :: ccs:'SubscricaoTaxaFixa'() | undefined % = 3
        }).
-endif.

-ifndef('LICITACAOLEILAO_PB_H').
-define('LICITACAOLEILAO_PB_H', true).
-record('LicitacaoLeilao',
        {empresa                :: iolist(),        % = 1
         montante               :: integer(),       % = 2, 32 bits
         taxa                   :: float() | integer() | infinity | '-infinity' | nan % = 3
        }).
-endif.

-ifndef('SUBSCRICAOTAXAFIXA_PB_H').
-define('SUBSCRICAOTAXAFIXA_PB_H', true).
-record('SubscricaoTaxaFixa',
        {empresa                :: iolist(),        % = 1
         montante               :: integer()        % = 2, 32 bits
        }).
-endif.

-ifndef('RESPOSTAEXCHANGE_PB_H').
-define('RESPOSTAEXCHANGE_PB_H', true).
-record('RespostaExchange',
        {tipo = 'RESULTADO'     :: 'RESULTADO' | 'NOTIFICACAO' | 'RESPOSTA' | integer(), % = 1, enum TipoResposta
         notificacao            :: ccs:'NotificacaoUltrapassado'() | undefined, % = 2
         resultado              :: ccs:'Resultado'() | undefined, % = 3
         resposta               :: ccs:'Resposta'() | undefined % = 4
        }).
-endif.

-ifndef('RESPOSTA_PB_H').
-define('RESPOSTA_PB_H', true).
-record('Resposta',
        {tipo = 'LEILAO'        :: 'LEILAO' | 'EMISSAO' | 'SUBSCRICAO' | integer(), % = 1, enum TipoMensagem
         utilizador             :: iolist(),        % = 2
         sucesso                :: boolean() | 0 | 1, % = 3
         mensagem               :: iolist() | undefined % = 4
        }).
-endif.

-ifndef('NOTIFICACAOULTRAPASSADO_PB_H').
-define('NOTIFICACAOULTRAPASSADO_PB_H', true).
-record('NotificacaoUltrapassado',
        {empresa                :: iolist(),        % = 1
         utilizador             :: iolist(),        % = 2
         taxa                   :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         valor                  :: integer(),       % = 4, 32 bits
         texto                  :: iolist() | undefined % = 5
        }).
-endif.

-ifndef('RESULTADO_PB_H').
-define('RESULTADO_PB_H', true).
-record('Resultado',
        {tipo = 'LEILAO'        :: 'LEILAO' | 'EMISSAO' | 'SUBSCRICAO' | integer(), % = 1, enum TipoMensagem
         empresa                :: iolist(),        % = 2
         texto                  :: iolist(),        % = 3
         sucesso                :: boolean() | 0 | 1 % = 4
        }).
-endif.

-ifndef('SUBSCRICAO_PB_H').
-define('SUBSCRICAO_PB_H', true).
-record('Subscricao',
        {tipo = 'LEILAOSUB'     :: 'LEILAOSUB' | 'EMISSAOSUB' | 'EMPRESASUB' | integer(), % = 1, enum TipoSubscricao
         eSubscricao            :: boolean() | 0 | 1, % = 2
         empresa                :: iolist() | undefined % = 3
        }).
-endif.

-endif.
